name: combined_environment
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - python=3.9.25
  - pip=25.3
  - pip:
    - absl-py==2.3.1
    - accelerate==1.10.1
    - aesthetic-predictor-v2-5==2024.12.18.1
    - anyio==4.12.0
    - args==0.1.0
    - astunparse==1.6.3
    - attrs==25.4.0
    - braceexpand==0.1.7
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - click==8.1.8
    - clint==0.5.1
    - clip==1.0
    - contourpy==1.3.0
    - cycler==0.12.1
    - diffusers==0.35.2
    - einops==0.8.1
    - exceptiongroup==1.3.1
    - ffmpeg-python==0.2.0
    - filelock==3.19.1
    - flatbuffers==25.9.23
    - fonttools==4.60.1
    - fsspec==2025.10.0
    - ftfy==6.3.1
    - future==1.0.0
    - gast==0.7.0
    - google-pasta==0.2.0
    - grpcio==1.76.0
    - h11==0.16.0
    - h5py==3.14.0
    - hf-xet==1.2.0
    - hpsv2==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - idna==3.11
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - iniconfig==2.1.0
    - jinja2==3.1.6
    - joblib==1.5.2
    - keras==3.10.0
    - kiwisolver==1.4.7
    - libclang==18.1.1
    - lightning-utilities==0.15.2
    - lpips==0.1.4
    - markdown==3.9
    - markdown-it-py==3.0.0
    - markupsafe==3.0.3
    - matplotlib==3.9.4
    - mdurl==0.1.2
    - ml-dtypes==0.5.4
    - mpmath==1.3.0
    - namex==0.1.0
    - networkx==3.2.1
    - numpy==2.0.2
    - opencv-python==4.12.0.88
    - opt-einsum==3.4.0
    - optree==0.18.0
    - packaging==25.0
    - pandas==2.3.3
    - pillow==11.3.0
    - pluggy==1.6.0
    - protobuf==3.20.3
    - psutil==7.1.3
    - pyarrow==21.0.0
    - pygments==2.19.2
    - pyparsing==3.2.5
    - pytest==7.2.0
    - pytest-split==0.8.0
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - regex==2025.11.3
    - requests==2.32.5
    - rich==14.2.0
    - safetensors==0.7.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - sentencepiece==0.2.1
    - shellingham==1.5.4
    - simple-aesthetics-predictor==0.1.2
    - six==1.17.0
    - sympy==1.14.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.20.0
    - termcolor==3.1.0
    - threadpoolctl==3.6.0
    - timm==1.0.22
    - tokenizers==0.22.1
    - tomli==2.3.0
    - torch==2.8.0
    - torchmetrics==1.8.2
    - torchvision==0.23.0
    - tqdm==4.67.1
    - transformers==4.57.3
    - triton==3.4.0
    - typer-slim==0.20.0
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - wcwidth==0.2.14
    - webdataset==0.2.100
    - werkzeug==3.1.4
    - wrapt==2.0.1
    - zipp==3.23.0
